
* Programa.: suizo80F.PRG
* Autor....: Juanjo ESCRIBANO LASA
* Fecha....: 03/12/91
* Aviso....: Copyright 19**, All Rights Reserved
* Objeto...: Generador de frames
*
@  2, 0 to 2,79 double
@  4, 0 SAY "Num_jug...:"
@  5, 0 SAY "Licencia..:"
@  6, 0 SAY "Nombre....:"
@  7, 0 SAY "Federacion:"
@  8, 0 SAY "Categoria.:"
@  9, 0 SAY "Elo_fide..:"
@ 10, 0 SAY "Elo_naci..:"
@ 11, 0 SAY "Elo_prov..:"
@ 12, 0 SAY "Oharra....:"
@ 20, 0 to 20,79 double
RETURN
* EOF: suizo80F.PRG
